# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
   include:     
     - main
  paths:
    include:
    - src

variables:
  buildConfiguration: 'Release'

stages:
  - stage: CI
    displayName: Build and test in a container
    jobs:
      - job: BuildAndTest
        pool:
          vmImage: ubuntu-latest          
        steps:                         
          - task: DotNetCoreCLI@2
            displayName: Restauracion de dependencias
            inputs:
              command: restore
              projects: src/**/*csproj
          - task: DotNetCoreCLI@2
            displayName: Compilacion de los proyectos
            inputs:
              command: build
              projects: src/**/*csproj
              arguments: '--configuration $(BuildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              projects: tests/**/*.csproj
              arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'
                   
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              publishWebProjects: False
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/SwimmingTool_$(Build.BuildNumber)'
              zipAfterPublish: True

          - task: PublishTestResults@2
            displayName: Publicacion de resultados de test
            inputs:
              buildConfiguration: $(BuildConfiguration)
              testResultsFormat: VSTest
              testResultsFiles: $(Agent.TempDirectory)/*.trx

          - task: PublishCodeCoverageResults@1 
            displayName: Publicar resultados de covertura
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(Agent.TempDirectory)/*.coverage

          - task: CopyFiles@2
            displayName: 'Copy build files'
            inputs:              
              TargetFolder: '$(build.artifactstagingdirectory)/build'
              CleanTargetFolder: true
              OverWrite: true
              
          - task: PublishBuildArtifacts@1
            displayName: Generando artefacto
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/SwimmingTool_$(Build.BuildNumber)'
              ArtifactName: 'SwimmingTool_LatestBuild'
              publishLocation: 'Container'

          - script: |
              docker-compose up --force-recreate --build --detach
            workingDirectory: .
            displayName: Lanzar Docker Compose

          - task: Bash@3
            displayName: Verificar Docker container
            inputs:
              targetType: inline
              script: |
                sleep 30
                testCondition=$(docker inspect --format="{{.State.Running}}" catalog_api)
                if [ "$testCondition" == "false" ]; then
                  echo "The container is not running" >&2
                  exit 1;
                else
                  echo "The container is running" >&2
                  exit 0
                fi
          - script: |
              docker-compose -f docker-compose.yml down
            displayName: Parar Docker compose
            workingDirectory: .
  
  - stage: CD
    jobs:
      - job: Docker
        displayName: Build and push container
        pool:
          vmImage: ubuntu-latest        
        steps:
          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              containerRegistry: 'jmhh-acr'
              repository: 'ClubNatacion'              
              Dockerfile: 'containers/api/Dockerfile'
              buildContext: 'src/'
              tags: |
                $(Build.BuildId)
                latest
          - task: Docker@2
            displayName: Push image
            inputs:
              containerRegistry: 'jmhh-acr'
              repository: 'ClubNatacion'
              command: push
              tags: |
                $(Build.BuildId)
                latest

      # - deployment: K8S_Desarrollo
      #   dependsOn: Docker
      #   displayName: Deploy to K8S develop cluster
      #   #condition: ne(variables['Build.SourceBranchName'], 'main')
      #   pool:
      #       vmImage: 'ubuntu-latest'      
      #   variables:
      #   - group: operadores_desarrollo
      #   environment: Desarrollo.default
      #   strategy:
      #     runOnce:
      #       deploy:
      #         steps:
      #           - checkout: self
      #           - task: Kubernetes@1
      #             displayName: Creacion del ConfigMap
      #             inputs:                  
      #               forceUpdateConfigMap: true
      #               configMapName: variablesentornooperadores
      #               configMapArguments: --from-literal=conexionrepositorio="$(CONNECTIONSTRINGOPERADORES)" 
      #               --from-literal=conexionrabbit="$(CONNECTIONRABBITMQ)" 
      #               --from-literal=instrumentationkey="$(INSTRUMENTATIONKEY)" 
      #               --from-literal=isactivated_gls_canalizaciones="$(ISACTIVATED_GLS_CANALIZACIONES)" 
      #               --from-literal=isactivated_gls_estados="$(ISACTIVATED_GLS_ESTADOS)" 
      #               --from-literal=isactivated_gls_registros="$(ISACTIVATED_GLS_REGISTROS)"
      #               --from-literal=isactivated_sending_canalizaciones="$(ISACTIVATED_SENDING_CANALIZACIONES)" 
      #               --from-literal=isactivated_sending_estados="$(ISACTIVATED_SENDING_ESTADOS)" 
      #               --from-literal=isactivated_sending_registros="$(ISACTIVATED_SENDING_REGISTROS)" 
      #               --from-literal=isactivated_tipsa_canalizaciones="$(ISACTIVATED_TIPSA_CANALIZACIONES)" 
      #               --from-literal=isactivated_tipsa_estados="$(ISACTIVATED_TIPSA_ESTADOS)" 
      #               --from-literal=isactivated_tipsa_registros="$(ISACTIVATED_TIPSA_REGISTROS)" 
      #               --from-literal=executiondelay_canalizaciones="$(EXECUTIONDELAY_CANALIZACIONES)" 
      #               --from-literal=executiondelay_estados="$(EXECUTIONDELAY_ESTADOS)" 
      #               --from-literal=executiondelay_registros="$(EXECUTIONDELAY_REGISTROS)" 
      #               --from-literal=usr_gls_api="$(USR_GLS_API)" 
      #               --from-literal=psw_gls_api="$(PSW_GLS_API)" 
      #               --from-literal=url_gls_api="$(URL_GLS_API)" 
      #               --from-literal=url_gls_envios_api="$(USR_GLS_ENVIOS_API)" 
      #               --from-literal=usr_sending_api="$(USR_SENDING_API)" 
      #               --from-literal=psw_sending_api="$(PSW_SENDING_API)" 
      #               --from-literal=url_sending_api="$(URL_SENDING_API)" 
      #               --from-literal=age_tipsa_api="$(AGE_TIPSA_API)" 
      #               --from-literal=cli_tipsa_api="$(CLI_TIPSA_API)" 
      #               --from-literal=psw_tipsa_api="$(PSW_TIPSA_API)" 
      #               --from-literal=url_tipsa_api="$(URL_TIPSA_API)" 
      #               --from-literal=url_tipsa_login_api="$(URL_TIPSA_LOGIN_API)" 
      #               --from-literal=url_tipsa_webservice_api="$(URL_TIPSA_WEBSERVICE_API)" 
      #               --from-literal=usuario_buzon_compartido="$(USUARIO_BUZON_COMPARTIDO)" 
      #               --from-literal=contrasena_buzon_compartido="$(CONTRASENA_BUZON_COMPARTIDO)" 
      #               --from-literal=email_buzon_compartido="$(EMAIL_BUZON_COMPARTIDO)" 
      #               --from-literal=url_servidor_exchange="$(URL_SERVIDOR_EXCHANGE)" 
      #               --from-literal=url_pedidos_web="$(URL_PEDIDOS_WEB)" 
      #               --from-literal=url_centros_web="$(URL_CENTROS_WEB)" 
      #               --from-literal=url_centro_web="$(URL_CENTRO_WEB)" 
      #           - task: KubernetesManifest@0
      #             displayName: Creacion del deployment y service
      #             inputs:
      #               action: deploy
      #               manifests: ./operadores.yml
      #               containers: drnacr.azurecr.io/operadores:$(Build.BuildId)

      #- deployment: K8S_Produccion
      # displayName: Deploy to K8S production cluster
        #condition: eq(variables['Build.SourceBranchName'], 'main')
        #pool:
        #    vmImage: 'ubuntu-latest'
        #environment: Produccion.default
        #variables:
        #- group: operadores_produccion
        #strategy:
        #  runOnce:
        #    deploy:
        #      steps:
        #        - checkout: self
        #        - task: Kubernetes@1
        #          displayName: Creacion del ConfigMap
        #          inputs:                  
        #            forceUpdateConfigMap: true
        #            configMapName: variablesentornooperadores
        #            configMapArguments: --from-literal=conexionrepositorio="$(CONNECTIONSTRINGOPERADORES)" --from-literal=conexionrabbit="$(CONNECTIONRABBITMQ)"

                #- task: KubernetesManifest@0
                # displayName: Creacion del deployment y service
                  #inputs:
                  # action: deploy
                    #manifests: ./operadores.yml
                    #containers: drnacr.azurecr.io/operadores:$(Build.BuildId)