name: Build
trigger: none

resources:
  pipelines:
    - pipeline: _SwimmingTool.Api.CI
      source: SwimmingTool.Api.CI
      branch: main
      trigger: true

    - pipeline: _SwimmingTool.Api.Config
      source: SwimmingTool.Api.Config
      branch: main
      trigger: true

stages:
  - stage: Build_Image
    displayName: Download artefact and build iamge
    jobs:
      - job: buildAndPush
        displayName: Build and publish Image
        pool: Default 
        steps:          
        - download: _SwimmingTool.Api.CI
          displayName: Download artefact
          artifact: 'SwimmingTool_LatestBuild'

        - download: _SwimmingTool.Api.Config
          displayName: Download config
          artifact: 'SwimmingTool_Config'

        - task: ExtractFiles@1
          displayName: 'Extract files from _SwimmingTool.Api.CI/SwimmingTool_LatestBuild/*.zip'
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/_SwimmingTool.Api.CI/SwimmingTool_LatestBuild/*.zip'
            destinationFolder: '$(Build.StagingDirectory)/SwimmingTool_LatestBuild'
            cleanDestinationFolder: true
          continueOnError: false

        - task: CopyFiles@2
          displayName: 'Copy Dockerfile file to $(Build.StagingDirectory)'
          inputs:
            SourceFolder: '$(Build.Repository.LocalPath)'
            Contents: 'Dockerfile'
            TargetFolder: '$(Build.StagingDirectory)'

        - task: Docker@2
          displayName: 'Build and publish image'
          inputs:
            command: buildAndPush
            containerRegistry: 'Jmhh-Production-Acr'
            repository: SwimmingTool
            Dockerfile: '$(Build.StagingDirectory)/Dockerfile'
            buildContext: '$(Build.StagingDirectory)'
            
        - task: DeleteFiles@1
          displayName: 'Delete files from _SwimmingTool.Api.CI/SwimmingTool_LatestBuild/*.zip'
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/_SwimmingTool.Api.CI/SwimmingTool_LatestBuild'
            Contents: '*.zip'

            