name: Build

resources:
  pipelines:
    - pipeline: _SwimmingTool.Api.CI
      source: SwimmingTool.Api.CI
      branch: main
      trigger: true

stages:
  - stage: Build_Image
    displayName: Download artefact and build iamge
    jobs:
      - job: 
        pool: Default 
        steps:          
        - download: _SwimmingTool.Api.CI
          artifact: 'SwimmingTool_LatestBuild'

        - task: ExtractFiles@1
          displayName: 'Extract files from _SwimmingTool.Api.CI/SwimmingTool_LatestBuild/*.zip'
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/_SwimmingTool.Api.CI/SwimmingTool_LatestBuild/*.zip'
            destinationFolder: '$(Build.StagingDirectory)/SwimmingTool_LatestBuild'
            cleanDestinationFolder: true
          continueOnError: true
        
        - task: DeleteFiles@1
          displayName: 'Delete files from _SwimmingTool.Api.CI/SwimmingTool_LatestBuild/*.zip'
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/_SwimmingTool.Api.CI/SwimmingTool_LatestBuild'
            Contents: '*.zip'