version: "3.7"
services:
  clubnatacion_api:
    container_name: catalog_api
    build: 
      context: .
      dockerfile: containers/api/Dockerfile
    env_file:
      - containers/api/api.env    
    ports:
      - 80:80
      - 443:443
    depends_on:
      - catalog_db

  catalog_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catalog_db
    ports:
      - 1433:1433
    env_file:
      - containers/db/db.env
    
