parameters:
  - name: pathToFiles
    type: string
  - name: artifactName
    type: string

trigger: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:   
    - publish: '$(Build.SourcesDirectory)/${{ parameters.pathToFiles }}'
      displayName: 'Publish script'
      artifact: ${{ parameters.artifactName }}

- stage: test
  dependsOn: build
  jobs:
  - job: run_test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: ${{ parameters.artifactName }}
      
    - powershell: |
        $bicepFiles = [string[]]$files = (Get-ChildItem '$(Pipeline.Workspace)/${{ parameters.pathToFiles }}').FullName
        $bicepFilesString = $bicepFiles -join "$"
        $bicepFilesString
        Write-Host "##vso[task.setvariable variable=bicepFiles;]$bicepFilesString"        
      displayName: 'PowerShell Script'
      
    - ${{ each bicepFile in split(variables.bicepFiles, '$') }}:
      - script: echo ${{ bicepFile }}
        displayName: 'Dinamyc Step'
    - bash: |
        echo "You can use macro syntax for variables: $(bicepFiles)"
