parameters:
  - name: pathToFiles
    type: string
  - name: artifactName
    type: string

trigger: none

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:   
    - publish: '$(Build.SourcesDirectory)/${{ parameters.pathToFiles }}'
      displayName: 'Publish script'
      artifact: ${{ parameters.artifactName }}

- stage: test
  dependsOn: build
  jobs:
  - job: run_test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: ${{ parameters.artifactName }}
      
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'Visual Studio Enterprise Subscription (2e763394-a7c4-49b0-845f-15f7caf388c5)'
        ScriptType: 'InlineScript'
        Inline: |
          $bicepFiles = (Get-ChildItem '$(Pipeline.Workspace)/${{ parameters.pathToFiles }}' -Filter *.bicep).FullName
          foreach($biceFile in $bicepFiles) {
              $bicepParamFile = $biceFile + "param"
              Get-Content $biceFile
              Get-Content $bicepParamFile
              New-AzResourceGroupDeployment -ResourceGroupName "jmhh-rsg-core" -TemplateFile "/home/vsts/work/1/iac/appckeyvalue.bicep" -TemplateParameterFile "/home/vsts/work/1/iac/appckeyvalue.bicepparam" -environment: "DEV"
          }
        azurePowerShellVersion: 'LatestVersion'
    
